#+OPTIONS: toc:nil
#+TITLE: Strona, wersja "cyryliczna"

** Skąd właściwie ta cyrylica?
Jest to kwestia złożona
1. ta strona to oryginalnie (de facto zaszły już srogie zmiany, w
   końcu może wejść w grę rodzaj /statku tezeusza/) była moja strona
   zaliczeniowa na lekcję informatyki w pierwszej liceum (polecam
   zobaczyć [[file:README_old.md][stare readme]] ~README_old.md~, które pochodzi z tamtych czasów
2. byłem fanem cyrylicy w czasach gdy to wszystko oryginalnie powstawało
3. był to 2017 rok

** Overview strony
Dokonałem dużej reorganizacji i szlifu w 2021 roku adaptując tę stronę
do celów obecnych. Zmiany zaszły na wielu polach:
a. dodałem stopkę z mailem zapisanym w rachunku \lambda, ale to
   kwestia chwilowego miłośnictwa będącego pochodną funkcyjności moich
   zainteresowań w ostatnim krótkim czasie
b. ~stylesheets~ są osobno w katalogu ~css~. Jest główny ~style.css~
   obowiązujący dla wszystkich podstron oraz personalne pomniejsze
   ceesesy według schematu: jeśli mamy stronę ~x.html~ to jej
   stylizacja to naczelny ~css/style.css~ oraz prywatny
   ~css/x.css~.
c. Cały javascript też ma własne składowisko (katalog ~js~)
d. ogólna renowacja stylu zaszła, ale nie było w tym rewolucji. Ogólny
   wygląd strony nadal w jakichś 70-80% zgadza się z oryginałem
   (zależy jak blisko oko przyłożyć)
e. użyłem [[https://katex.org][KaTeXa]] na jednej z podstron, ale nie wiem jak go nauczyć
   użytku znaku z utf-8 (tak dokładnie to litery /ę/) wewnątrz
   mathmode'u. jeśli ktoś wie to proszę o informację!
f. zalinkowałem wiele fajnych rzeczy

** jaka jest przyszłość?
*** przejście na coś lepszego?
myślałem o całkowitym porzuceniu tej strony i przejściu na jakąś
advanced technologię pokroju [[https://jekyllrb.com][jekylla]]. Przyznam, że zainspirował mnie
do tego pan dziekan [[https://www.mimuw.edu.pl/~pawelst/blog/2020/newpage/][opisując swoje trudny webdevowe]] xd. Najchętniej
pisałbym to w [[https://orgmode.org/][orgu]], ale z tym zawsze się wiążą jakieś
komplikacje. Choć chyba da się do jekylla, ale może w grę wchodzą
jakieś mniej fancy technologie np [[https://github.com/novoid/lazyblorg][lazyblorg]]. 
*** rozbudowa obecnego status quo?
**** rewolucyjnie
Całkowite zamieszanie wewnątrz struktury obecnej?
**** reformacyjnie
Ulepszać krok po kroku tę stronę?
*** całkowicie nowa strona odręczna?
Obecnie to poza moim zasięgiem oraz chęcią. *Nie lubię webdevu*. 
Jednakże może w dalszej przyszłości najdzie mi na to ochota, kto wie.
*** ktoś mi zrobi stronę
kontrowersyjna opcja i raczej wolałbym tego uniknąć xd


