#+OPTIONS: toc:nil
#+TITLE: Strona, wersja "cyryliczna"

** Skąd właściwie ta cyrylica?
Jest to kwestia złożona
+ ta strona to oryginalnie (de facto zaszły już srogie zmiany, w
  końcu może wejść w grę rodzaj /statku tezeusza/) była moja strona
  zaliczeniowa na lekcję informatyki w pierwszej liceum (polecam
  zobaczyć [[file:old/README_old.md][stare readme]] ~old/README_old.md~, które pochodzi z tamtych czasów
+ byłem fanem cyrylicy w czasach gdy to wszystko oryginalnie powstawało
+ był to 2017 rok

** Overview strony
Dokonałem dużej reorganizacji i szlifu w 2021 roku adaptując tę stronę
do celów obecnych. Zmiany zaszły na wielu polach:
1. dodałem stopkę z mailem zapisanym w rachunku \lambda, ale to
   kwestia chwilowego miłośnictwa będącego pochodną funkcyjności moich
   zainteresowań w ostatnim krótkim czasie
2. ~stylesheets~ są osobno w katalogu ~css~. Jest główny ~style.css~
   obowiązujący dla wszystkich podstron oraz personalne pomniejsze
   ceesesy według schematu: jeśli mamy stronę ~x.html~ to jej
   stylizacja to naczelny ~css/style.css~ oraz prywatny
   ~css/x.css~.
3. Cały javascript też ma własne składowisko (katalog ~js~)
4. ogólna renowacja stylu zaszła, ale nie było w tym rewolucji. Ogólny
   wygląd strony nadal w jakichś 70-80% zgadza się z oryginałem
   (zależy jak blisko oko przyłożyć)
5. użyłem [[https://katex.org][KaTeXa]] na jednej z podstron, ale nie wiem jak go nauczyć
   użytku znaku z utf-8 (tak dokładnie to litery /ę/) wewnątrz
   mathmode'u. jeśli ktoś wie to proszę o informację!
6. zalinkowałem wiele fajnych rzeczy
**** *orgise*
*Orgise* to (tępe) narzędzie jakie napisałem w *ruby* na potrzeby
 głównie [[file:blog][bloga]], ale przyda się ogólnie -- lepsze od pisania w syfnym
 htmlu. Większy [[https://students.mimuw.edu.pl/~gc429174/cyr/blog#orgise][opis tutaj na blogu.]]
** jaka jest przyszłość?
*** przejście na coś lepszego?
myślałem o całkowitym porzuceniu tej strony i przejściu na jakąś
advanced technologię pokroju [[https://jekyllrb.com][jekylla]]. Przyznam, że zainspirował mnie
do tego pan dziekan [[https://www.mimuw.edu.pl/~pawelst/blog/2020/newpage/][opisując swoje trudny webdevowe]] xd. Najchętniej
pisałbym to w [[https://orgmode.org/][orgu]], ale z tym zawsze się wiążą jakieś
komplikacje. Choć chyba da się do jekylla, ale może w grę wchodzą
jakieś mniej fancy technologie np [[https://github.com/novoid/lazyblorg][lazyblorg]]. 
*** rozbudowa obecnego status quo?
**** rewolucyjnie
Całkowite zamieszanie wewnątrz struktury obecnej?
**** reformacyjnie
Ulepszać krok po kroku tę stronę?

Do ulepszenia:
1. +ustawienia menu mogłyby być lepiej zrobione+ -- już zrobione
2. duże porcje strony się pokrywają -- system jakichś include'ów?
3. podstrona *dydaktyka*, ale nie wiem co bym tam trzymał...
4. zrobić dla katalofu ~koty~ galerię zdjęć w jakimś
   ~index.html~. Musiałbym coś jak [[https://stackoverflow.com/a/52473157][tutaj ukazane]] zrobić.
5. to akurat oczywista zmiana. w menu ~index.html~ usunąć osobny link
   do /fajnych rzeczy/. Byłaby to wciąż osobna sekcja, ale link do
   rzeczy służyłby również do niej. Zamiast tego wolne miejsce
   wykorzystałbym albo na dydaktykę (vide punkt 3.) albo na jakąś
   stronę typu /inne/, która by linkowała do /innych/. W ogólności co
   właściwie jest potrzebne na takiej stronie głównej?
   + link do niej samej
   + link do jakiegoś /about/
   + link do /rzeczy/ chciałbym zostawić, tam mógłbym osobną listę
     podstron wykonać w zasadzie
   + *dydaktyka*, ale bez contentu trochę głupio...
   + strona sekretna mogłaby zostać
   + cyrylarz ma miejsce honorowe... ale czy musi być w menu? do
     rozważenia
6. bądź co bądź w menu każdej strony powinno być od 1 do 5 (+1) pól
*** całkowicie nowa strona odręczna?
Obecnie to poza moim zasięgiem oraz chęcią. *Nie lubię webdevu*. 
Jednakże może w dalszej przyszłości najdzie mi na to ochota, kto wie.
*** ktoś mi zrobi stronę
kontrowersyjna opcja i raczej wolałbym tego uniknąć xd


